# Generated by Django 5.0.2 on 2024-06-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['sort'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='category',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='Sort'),
        ),
        migrations.AddField(
            model_name='product',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='Sort'),
        ),
    ]
