# Generated by Django 5.0.2 on 2024-07-17 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_image_for_bracelet'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.material'),
        ),
    ]
