# Generated by Django 5.0.2 on 2024-08-04 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_category_is_bracelet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_for_bracelet',
        ),
    ]
