# Generated by Django 5.0.2 on 2024-05-26 20:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_contact_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('photo', models.FileField(upload_to='about_images', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'About Us Image',
                'verbose_name_plural': 'About Us Images',
            },
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_text',
            field=models.TextField(blank=True, verbose_name='Meta Text'),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Meta Title'),
        ),
    ]
