# Generated by Django 5.0.2 on 2024-05-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_page_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutimage',
            name='photo',
        ),
        migrations.AddField(
            model_name='aboutimage',
            name='image',
            field=models.ImageField(null=True, upload_to='about_images', verbose_name='Image'),
        ),
    ]
