# Generated by Django 5.0.2 on 2024-06-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_aboutimage_photo_aboutimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(null=True, upload_to='contact_images', verbose_name='Image'),
        ),
    ]
