# Generated by Django 5.0.2 on 2024-06-02 10:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_aboutimage_options_aboutimage_sort'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('contact_form_title', models.CharField(blank=True, max_length=100, verbose_name='Contact Form Title')),
                ('contact_form_text', models.TextField(blank=True, verbose_name='Contact Form Text')),
                ('contact_email', models.CharField(max_length=100, verbose_name='Contact Email')),
                ('footer_address', models.TextField(blank=True, verbose_name='Footer Address')),
                ('footer_copyright', models.CharField(blank=True, max_length=100, verbose_name='Footer Copyright')),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
