# Generated by Django 5.0.2 on 2024-09-18 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_social'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Request', 'verbose_name_plural': 'Contact Requests'},
        ),
    ]
