# Generated by Django 5.0.2 on 2024-06-26 12:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('shop', '0004_category_is_constructor_bracelet'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBracelet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('bracelet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.bracelet')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bracelets', to='order.order')),
            ],
            options={
                'verbose_name': 'Order Bracelet',
                'verbose_name_plural': 'Order Bracelets',
            },
        ),
    ]
