# Generated by Django 5.0.2 on 2025-05-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='ring_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
