# Generated by Django 5.0.2 on 2025-10-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_orderproduct_ring_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name and surname'),
        ),
    ]
